name: plant-stylist
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - python-fasthtml
    - requests
    - python-multipart
    - python-dotenv
    - google-generativeai
    - langchain
    - langchain-google-genai
    - langgraph
